sudo: required
services:
  - docker

before_install: 
  - docker build -t raanan7784/docker-kebernetes-cicd -f Dockerfile.dev .

script: 
  - docker run -e CI=true raanan7784/docker-kebernetes-cicd npm run test