sudo: required
services:
  - docker

before_install: 
  - docker build -t raanan7784/docker-kebernetes-cicd -f Dockerfile.dev .

script: 
  - docker run -e CI=true raanan7784/docker-kebernetes-cicd npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-cicd"
  env: "Docker-cicd-env"
  bucket_name: "elasticbeanstalk-us-east-1-637423406664"
  bucket_path: "Docker-cicd"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

